### ISSUE TITLE
can you offer the trained model?

### ISSUE THREAD

**Issue by cooper12121** [truas/LexicalChain_Builder#1]
Excuse me,can you offer the trained model of this project?
thank you

**Comment by truas** [comment]
Hi @cooper12121 !

All the models are on the repository we list on the readme of the project right here: https://deepblue.lib.umich.edu/data/concern/data_sets/w9505046h?locale=en . Under [synset-models.zip](https://deepblue.lib.umich.edu/data/downloads/d791sg19j). In case the models are not there let me know. I can try to recover from my backups.

Regards,
T.

**Comment by truas** [comment]
I'll close this issue, but in case it does not work please get in touch
